export const READ_COMMANDS = [
  "list_components",
  "get_component_detail",
  "search_components",
  "get_plugin_catalog",
  "get_plugin_manifest",
  "search_plugins",
  "get_capability_overview",
  "search_capabilities",
  "search_findings",
  "search_alerts",
  "search_incidents",
  "get_incident_detail",
  "search_flows",
  "search_dns",
  "search_tls",
  "get_graph_view",
  "list_active_responses",
  "search_response_plans",
  "list_reports",
  "search_reports",
  "get_report",
  "get_attack_coverage_summary",
  "get_fusion_summary",
  "list_security_facts",
  "list_attack_hypotheses",
  "get_attack_hypothesis",
  "get_durable_baseline_summary",
  "get_evidence_quality_summary",
  "list_evidence_quality_records",
  "get_evidence_quality_record",
  "get_investigation_drill_down_summary",
  "resolve_navigation_reference",
  "get_hypothesis_explanation_detail",
  "get_baseline_drill_down_detail",
  "get_incident_group_investigation_detail",
  "get_timeline_drill_down_detail",
  "get_source_reliability_explanation",
  "list_baseline_records",
  "get_baseline_record",
  "list_baseline_indicators",
  "get_baseline_indicator",
  "list_incident_linked_hypothesis_groups",
  "get_incident_linked_hypothesis_group",
  "list_incident_timeline_entries",
  "get_incident_timeline_entry",
  "list_source_reliability_summaries",
  "get_metadata_watch_controller_status",
  "list_metadata_watch_sources",
  "get_metadata_watch_source",
  "list_metadata_sampling_batches",
  "get_metadata_sampling_batch",
  "list_export_history",
  "search_export_history",
  "get_export_history_record",
  "list_export_policy_violations",
  "get_runtime_profile",
  "search_runtime_profiles",
  "get_llm_alert_story_status",
  "list_llm_alert_stories",
  "get_llm_alert_story",
  "get_service_status",
  "search_service_status",
  "list_authorized_native_capabilities",
  "get_authorized_native_capability",
  "get_native_permission_status_summary",
  "get_native_visibility_summary",
  "get_native_permission_audit_summary",
  "list_native_sampler_contracts",
  "get_native_sampler_contract",
  "get_native_sampler_readiness_summary",
  "get_native_sampler_readiness_detail",
  "get_native_sampler_authorization_review",
  "get_future_security_fact_mapping_summary",
  "get_native_sampler_blocked_summary",
  "get_missing_endpoint_visibility_summary",
  "get_edr_readiness_summary",
  "get_native_sampler_runtime_summary",
  "get_native_sampler_runtime_status",
  "get_latest_native_sampler_runtime_batch",
  "get_native_scheduler_status",
  "list_native_sampler_schedule_statuses",
  "get_native_sampler_schedule_status",
  "get_native_scheduler_summary",
  "get_native_scheduler_operational_summary",
  "get_portable_preferences",
] as const;

export const MUTATION_COMMANDS = [
  "enable_plugin",
  "disable_plugin",
  "restart_plugin",
  "suppress_finding",
  "dismiss_finding",
  "escalate_alert",
  "update_incident_status",
  "create_response_plan",
  "approve_response_action",
  "reject_response_action",
  "rollback_response_action",
  "generate_incident_report",
  "export_report",
  "get_local_metadata_proxy_status",
  "start_local_metadata_proxy",
  "stop_local_metadata_proxy",
  "drain_local_metadata_proxy",
  "preview_portable_capture_import",
  "confirm_portable_capture_import",
  "preview_metadata_watch_source",
  "confirm_metadata_watch_source",
  "update_metadata_watch_source",
  "tick_metadata_watch_controller",
  "update_metadata_sampling_loop",
  "run_metadata_sampling_loop",
  "preview_explicit_export",
  "confirm_explicit_export",
  "apply_runtime_profile",
  "update_privacy_policy",
  "update_response_policy",
  "enable_forensic_mode",
  "disable_forensic_mode",
  "update_llm_alert_story_settings",
  "save_llm_alert_story_api_key",
  "clear_llm_alert_story_api_key",
  "test_llm_alert_story_connection",
  "generate_llm_alert_story",
  "preview_native_permission_request",
  "update_native_permission",
  "preview_native_sampler_activation",
  "apply_native_sampler_runtime_action",
  "preview_native_scheduler_enablement",
  "apply_native_scheduler_action",
  "run_demo_story",
  "save_portable_preferences",
  "shutdown_app",
] as const;

export type ReadCommandName = (typeof READ_COMMANDS)[number];
export type MutationCommandName = (typeof MUTATION_COMMANDS)[number];
export type CoreCommandName = ReadCommandName | MutationCommandName;

const COMMANDS = new Set<string>([...READ_COMMANDS, ...MUTATION_COMMANDS]);

const FORBIDDEN_COMMAND_MARKERS = [
  "firewall",
  "qos",
  "windivert",
  "sqlite",
  "raw_packet",
  "raw_payload",
  "payload_blob",
  "service_execute",
  "execute_response_action",
];

export function assertCoreCommandAllowed(
  command: string,
): asserts command is CoreCommandName {
  const normalized = command.toLowerCase();
  if (
    !COMMANDS.has(command) ||
    FORBIDDEN_COMMAND_MARKERS.some((marker) => normalized.includes(marker))
  ) {
    throw new Error(`Command is not exposed through the safe Rust Core bridge: ${command}`);
  }
}
